print("Hello my name is Susan from space")
print("What is your name? ")
name = input()
print(f"Hello {name}. I am from the year 2210 and I am 20 years old")
print("How old are you? ")
age = int(input())
future_age = age+(2210-2022)
print(f"Wow, by 2210, you will be {future_age}. That is really old.")
print("What music are you into?")
music = input()
print(f"I have not heard of {music}")
